FROM python:3.11-slim
WORKDIR /app
COPY shared/ ./shared/
COPY analysis_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY analysis_service/ ./analysis_service/
CMD ["uvicorn", "analysis_service.app.main:app", "--host", "0.0.0.0", "--port", "8002"]
